// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.team4230.ScaleBot;

import com.kauailabs.navx.frc.AHRS;

import edu.wpi.first.wpilibj.DigitalInput;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    public static int driveTrainR1 = 1;
    public static int driveTrainR2 = 2;
    public static int driveTrainL1 = 9;
    public static int driveTrainL2 = 8;
    public static AHRS gyro;

    public static DigitalInput LimitSwitchtop;
    public static DigitalInput LimitSwitchbottom;
    public static void init() {
    	LimitSwitchtop = new DigitalInput(1);
    	LimitSwitchbottom = new DigitalInput(2);
    }
}
